# Generated by Django 3.2.22 on 2023-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=64)),
                ('destino', models.CharField(max_length=64)),
                ('duracion', models.IntegerField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('vuelo', models.ManyToManyField(blank=True, related_name='pasajeros', to='core.Vuelo')),
            ],
        ),
    ]
