# Generated by Django 3.2.22 on 2023-10-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vuelos'),
        ),
    ]
