# Generated by Django 3.2.22 on 2023-10-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
